apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: skkj2eu9a-python
  janus-idp.io/tekton: skkj2eu9a-python
  backstage.io/kubernetes-id: skkj2eu9a-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: skkj2eu9a-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
